### PR TITLE
fix: Let nx-datasets respect XDG cache locations

### LINKED ISSUE #77: Let nx-datasets respect XDG cache locations
## Why it matters
Right now `Dataset_utils.get_cache_dir` always expands to `~/.cache/ocaml-nx/datasets/...` (see `nx-datasets/lib/dataset_utils.ml:54-62`). That ignores both `XDG_CACHE_HOME` and any custom cache path users set for sandboxed environments. Outreachy applicants working on shared machines or CI systems need to redirect downloads to writable directories without patching the code.

## How to reproduce
1. Run `XDG_CACHE_HOME=/tmp/outreachy-cache dune utop nx-datasets`.
2. Evaluate `Nx_datasets.Dataset_utils.get_cache_dir "iris";;` — it still prints a path under `~/.cache/ocaml-nx/` instead of `/tmp/outreachy-cache/...`.
3. The behaviour is the same even if you set `NX_DATASETS_CACHE`, because the code never checks that variable.

## Your task
- Update `nx-datasets/lib/dataset_utils.ml` so cache resolution prefers, in order:
  1. `NX_DATASETS_CACHE` (if set)
  2. `XDG_CACHE_HOME` (if set)
  3. Fall back to `$HOME/.cache`
- Make sure the calculation happens each time we call `get_cache_dir` (a helper function returning a string is fine) so tests can override the env at runtime.
- Keep the trailing slash in the returned path, and keep creating directories the same way.
- Document the new lookup order in `nx-datasets/lib/dataset_utils.mli`.
- Add an Alcotest case (e.g. `test_dataset_utils.ml`) that temporarily sets the env vars with `Unix.putenv`, calls `get_cache_dir`, and asserts the path prefix matches the env you set. Remember to restore the old values at the end of the test so other cases are not polluted.

## Tips
- `Sys.getenv_opt` (available since OCaml 4.06) is handy for optional environment variables.
- Prefer `Filename.concat` when stitching parts so Windows paths keep working.
- In tests, wrap env changes with `Fun.protect` to restore the original values even if the assertion fails.
- Run `dune runtest nx-datasets` to make sure the new test and the existing generator suite stay green.

## Done when
- Calling `get_cache_dir` honours `NX_DATASETS_CACHE`/`XDG_CACHE_HOME` when they are set, and still falls back to the old behaviour otherwise.
- The updated `.mli` explains the precedence clearly.
- The new unit test fails on the current main branch and passes after your changes.

### PR DESCRIPTION
**Pull request by Arsalaan-Alam**
This PR fixes #77 

Changes made:
- Updatd get_cache_dir function to check NX_DATASETS_CACHE (highest priority)
- Falls back to XDG_CACHE_HOME if NX_DATASETS_CACHE is not set
- Defaults to $HOME/.cache if neither env variable is set
- Added a unit test that covers all three scenarios
- Updated interface documentation with clear precedence order
- Exposed get_cache_dir through main nx_datasets module for testing

### CODE REVIEW

File: nx-datasets/lib/dataset_utils.ml [hunk 1]
```diff
@@ -51,15 +51,29 @@ let mkdir_p path perm =
...
     ()
 
-module Xdg = struct
-  let home =
-    try Sys.getenv "HOME"
-    with Not_found -> failwith "HOME environment variable not set."
-
-  let cache_base = home ^ "/.cache/ocaml-nx/datasets/"
-end
+let get_cache_base_dir () =
```
Comment (tmattio) [inline nx-datasets/lib/dataset_utils.ml]: Have you considered using `xdg` here? We might not want to add a new dependency but I think it's a single module so we could vendor it.

File: nx-datasets/lib/dataset_utils.ml [hunk 2]
```diff
@@ -51,15 +51,29 @@ let mkdir_p path perm =
...
+  match Sys.getenv_opt "NX_DATASETS_CACHE" with
```
Comment (tmattio) [inline nx-datasets/lib/dataset_utils.ml]: 👍

File: CHANGES.md [hunk 3]
```diff
@@ -86,6 +86,7 @@ All notable changes to this project will be documented in this file.
 
 ### Nx-datasets
 
+- Fix cache directory resolution to respect `NX_DATASETS_CACHE` and `XDG_CACHE_HOME` environment variables, allowing custom cache locations. (@Arsalaan-Alam)
```
Comment (tmattio) [inline CHANGES.md]: Need the number of the PR

File: nx-datasets/lib/dataset_utils.ml (hunk 1 above)
Comment (Arsalaan-Alam) [reply nx-datasets/lib/dataset_utils.ml]: vendored XDG, used source code from here: https://github.dev/ocaml/dune/otherlibs/xdg

**Comment by Arsalaan-Alam** [comment]
did the changes

**Comment by tmattio** [comment]
Thanks, in the end I think your idea of exposing a single `get_cache_dir` was a good compromise, so I restored a test file and pushed some minor changes.

**Comment by Arsalaan-Alam** [comment]
nice! oops i forgot to add the license
